version: "3.2"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elasticnet
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - elasticnet
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch 

  eth-relay:
    container_name: eth-relay
    build:
      context: ./eth-relay
    environment: 
      ELASTICSEARCH_ADDR: localhost:9200
      ETH_RPC_ADDR: ${ETH_RPC_ADDR}
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

networks:
  elasticnet:
    driver: bridge

volumes:
  elasticsearch: