version: "3.2"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  geth:
    container_name: geth
    image: ethereum/client-go
    volumes:
      - type: volume
        source: geth
        target: /root
    ports:
      - 8545:8545
      - 30303:30303
    command: --http --http.addr geth --syncmode light --http.corsdomain * --http.vhosts *

  eth-relay:
    container_name: eth-relay
    build:
      context: ./eth-relay
    environment:
      ELASTICSEARCH_ADDR: ${ELASTICSEARCH_ADDR}
      ETH_RPC_ADDR: ${ETH_RPC_ADDR}
      RELAY_INTERVAL: ${RELAY_INTERVAL}
      RELAY_BLOCK_START: ${RELAY_BLOCK_START}
      RELAY_BLOCK_END: ${RELAY_BLOCK_END}
    depends_on:
      - elasticsearch
    restart: on-failure

volumes:
  elasticsearch:
  geth:
